import './globals.css'
import { Inter } from 'next/font/google'
import ResponsiveAppBar from './navbar/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio by Gary Hui',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  )
}
